services:
  vibing2:
    build:
      context: .
    environment:
      NODE_ENV: production
      BOT_TOKEN: DISCORD_BOT_TOKEN
      CLIENT_ID: DISCORD_CLIENT_ID
      SESSION_SECRET: EXPRESS_SESSION_SECRET
      URL: https://example.org
      #PORT: 4321 # Optional, sets the internal port, defaults to 4321

    ports:
      - 4321:4321
